src/Entity/Order.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\OrderRepository;
use App\ValueObject\CouponCode;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\OneToMany;
use Doctrine\ORM\Mapping\PrePersist;
use Doctrine\ORM\Mapping\Table;

/** @psalm-suppress PropertyNotSetInConstructor */
#[Entity(repositoryClass: OrderRepository::class)]
#[Table(name: 'orders', schema: 'interview')]
#[HasLifecycleCallbacks]
class Order
{
    final public const PENDING = 'pending';

    final public const PROCESSING = 'processing';

    final public const COMPLETED = 'completed';

    final public const CANCELLED = 'cancelled';

    #[Id]
    #[GeneratedValue(strategy: 'SEQUENCE')]
    #[Column(name: 'order_id', type: Types::INTEGER, unique: true, nullable: false)]
    private int $id;

    #[Column(name: 'user_id', type: Types::INTEGER)]
    private int $userId;

    #[Column(name: 'netAmount', type: Types::INTEGER)]
    private int $netAmount;

    #[Column(name: 'shipping_cost', type: Types::INTEGER)]
    private int $shippingCost;

    #[Column(name: 'amount', type: Types::INTEGER)]
    private int $total;

    #[Column(name: 'status', type: Types::STRING, length: 25)]
    private string $status = self::PENDING;

    /** @var Collection<int, OrderItem> */
    #[OneToMany(mappedBy: 'order', targetEntity: OrderItem::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    private Collection $items;

    /** @var Collection<int, Payment> */
    #[OneToMany(mappedBy: 'order', targetEntity: Payment::class, orphanRemoval: true)]
    private Collection $payments;

    #[Column(name: 'coupon_type', type: Types::STRING, length: 25, nullable: true)]
    private ?string $couponType = null;

    #[Column(name: 'coupon_discount', type: Types::INTEGER, nullable: true)]
    private ?int $couponDiscount = null;

    private ?CouponCode $coupon = null;

    #[ManyToOne(targetEntity: Address::class, cascade: ['persist'])]
    #[JoinColumn(name: 'delivery_address_id', referencedColumnName: 'address_id', unique: false, nullable: false)]
    private Address $deliveryAddress;

    #[ManyToOne(targetEntity: Address::class, cascade: ['persist'])]
    #[JoinColumn(name: 'biling_address_id', referencedColumnName: 'address_id', unique: false, nullable: false)]
    private Address $bilingAddress;

    #[Column(name: 'created_at', type: Types::DATETIME_IMMUTABLE, options: ['default' => 'CURRENT_TIMESTAMP'])]
    private DateTimeImmutable $createdAt;

    public function __construct(
        int $netAmount,
        int $userId,
        int $shippingCost,
        int $total,
        Address $deliveryAddress,
        Address $bilingAddress,
    ) {
        $this->userId = $userId;
        $this->netAmount = $netAmount;
        $this->shippingCost = $shippingCost;
        $this->total = $total;

        $this->deliveryAddress = $deliveryAddress;
        $this->bilingAddress = $bilingAddress;

        $this->payments = new ArrayCollection();
        $this->items    = new ArrayCollection();

        $this->createdAt = new DateTimeImmutable();
    }

    public function applyCoupon(?CouponCode $coupon): void
    {
        if (null === $coupon) {
            $this->couponType = null;
            $this->couponDiscount = null;

            return;
        }

        $this->couponType = $coupon->getType();
        $this->couponDiscount = $coupon->getValue();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getUserId(): int
    {
        return $this->userId;
    }

    public function setUserId(int $userId): void
    {
        $this->userId = $userId;
    }

    public function getNetAmount(): int
    {
        return $this->netAmount;
    }

    public function getShippingCost(): int
    {
        return $this->shippingCost;
    }

    public function addItem(OrderItem $orderItem): void
    {
        $this->getItems()->add($orderItem);
    }

    /** @return Collection<int, OrderItem> */
    public function getItems(): Collection
    {
        return $this->items;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    #[PrePersist]
    public function prePersist(): void
    {
        $this->createdAt = new DateTimeImmutable();
    }

    public function addPayment(Payment $payment): void
    {
        $payment->setOrder($this);
        $this->payments->add($payment);
    }

    public function getLastPayment(): ?Payment
    {
        $payment = $this->payments->last();
        if (false === $payment) {
            return null;
        }

        return $payment;
    }

    public function getCreatedAt(): DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getDeliveryAddress(): Address
    {
        return $this->deliveryAddress;
    }

    public function setDeliveryAddress(Address $address): void
    {
        $this->deliveryAddress = $address;
    }

    public function getBilingAddress(): Address
    {
        return $this->bilingAddress;
    }

    public function setBilingAddress(Address $address): void
    {
        $this->bilingAddress = $address;
    }

    public function getCoupon(): ?CouponCode
    {
        if (null === $this->couponType || null === $this->couponDiscount) {
            return null;
        }

        $this->coupon = new CouponCode(type: $this->couponType, value: $this->couponDiscount);

        return $this->coupon;
    }

    public function getTotal(): int
    {
        return $this->total;
    }
}

src/Controller/OrderController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Order;
use App\Exception\Contracts\OrderOperationExceptionInterface;
use App\Form\PaymentType;
use App\Model\User;
use App\Requests\PaymentTypeRequest;
use App\Service\CalculatorService;
use App\Service\OrderService;
use App\Workflow\OrderWorkflow;
use Symfony\Component\Form\ClickableInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\AsController;
use Symfony\Component\HttpKernel\Attribute\MapRequestPayload;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\CurrentUser;
use Symfony\Component\Security\Http\Attribute\IsGranted;

use function assert;

#[AsController]
#[Route(path: '/order', name: 'order_', methods: ['GET', 'POST'])]
#[IsGranted(attribute: 'ROLE_USER', statusCode: 401)]
final class OrderController extends AbstractShopController
{
    #[Route(path: '/create/', name: 'create_pending', methods: ['POST'])]
    public function createPendingOrder(
        #[MapRequestPayload]
        PaymentTypeRequest $paymentType,
        OrderWorkflow $orderWorkflow,
    ): Response {
        try {
            $pendingOrder = $orderWorkflow->createPendingOrder($paymentType->getPaymentType());
        } catch (OrderOperationExceptionInterface $orderOperationException) {
            $this->addFlash('error', $orderOperationException->getMessage());

            return $this->redirectToRoute('checkout_index');
        }

        return $this->redirectToRoute(
            'order_pending',
            [
                'id' => $pendingOrder->getId(),
            ],
        );
    }

    #[Route(path: '/pending/{id}', name: 'pending', requirements: ['id' => '\d+'], methods: ['GET', 'POST'])]
    public function pending(Request $request, Order $order, OrderWorkflow $orderWorkflow): Response
    {
        $this->denyAccessUnlessGranted('view', $order, 'Access denied: You can only view pending orders.');

        $payment = $order->getLastPayment();
        $form    = $this->createForm(PaymentType::class, $payment);

        $form->handleRequest($request);
        if (true === $form->isSubmitted() && true === $form->isValid()) {
            $button = $form->get('yes');
            assert($button instanceof ClickableInterface);
            if (true === $button->isClicked()) {
                $orderWorkflow->confirmOrder($order);
            }

            return $this->redirectToRoute('order_summary', ['id' => $order->getId()]);
        }

        return $this->render(
            'order/payment.html.twig',
            [
                'order'   => $order,
                'payment' => $payment,
                'form'    => $form->createView(),
            ],
        );
    }

    #[Route(path: '/summary/{id}', name: 'summary')]
    public function summaryOrder(
        int $id,
        OrderService $orderService,
        CalculatorService $cartCalculatorService,
    ): Response {
        $order = $orderService->fetchOrderDetails($id);
        assert($order instanceof Order);

        return $this->render(
            'order/summary.html.twig',
            [
                'order' => $order,
                'summary' => $cartCalculatorService->calculateSummary($order->getNetAmount(), $order->getCoupon()),
            ],
        );
    }

    #[Route(path: '/orders/{page<\d+>}', name: 'index')]
    public function index(int $page, #[CurrentUser] User $user, OrderService $service): Response
    {
        $orders = $service->fetchOrders($user->getId(), $page);

        return $this->render(
            'order/index.html.twig',
            ['paginator' => $orders],
        );
    }

    #[Route(path: '/{id<\d+>}', name: 'details')]
    public function show(int $id, OrderService $orderService): Response
    {
        return $this->render(
            'order/details.html.twig',
            ['order' => $orderService->fetchOrderDetails($id)],
        );
    }
}

templates/order/details.html.twig
{% extends 'logged.html.twig' %}

{% block title %}Orders{% endblock %}

{% block body %}
    <div class="d-flex flex-column justify-content-center align-items-center" id="order-heading">
        <div class="text-uppercase">
            <p>Order detail</p>
        </div>
        <div class="h4">{{ order.createdAt|date("Y-m-d") }}</div>
        <div class="pt-1">
            <p>Order #{{ order.id }} is currently<b class="text-dark"> {{ order.status }}</b></p>
        </div>
    </div>
    <div class="wrapper bg-white">
        <div class="table-responsive">
            <table class="table table-borderless">
                <thead>
                <tr class="text-uppercase text-muted">
                    <th scope="col">product</th>
                    <th scope="col" class="text-right">total</th>
                </tr>
                </thead>
                <tbody>
                {% for item in order.items %}
                    <tr>
                        <th scope="row">{{ item.getDisplayName }}</th>
                        <td class="text-right"><b>{{ item.getUnitPrice(true)|format_currency("USD") }}</b></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="pt-2 border-bottom mb-3"></div>
        <div class="d-flex justify-content-start align-items-center pl-3">
            <div class="text-muted">Payment Method</div>
            <div class="ml-auto">
                <img src="https://www.freepnglogos.com/uploads/mastercard-png/mastercard-logo-logok-15.png" alt=""
                     width="30" height="30">
                <label>Online {{ order.getLastPayment().getStatus() }}</label>
            </div>
        </div>
        <div class="d-flex justify-content-start align-items-center py-1 pl-3 mx-1">
            <div class="text-muted">Shipping&nbsp;</div>
            <div class="ml-2">
                <label>Free</label>
            </div>
        </div>
        {# That will be usefull for vouchers feature #}
        {#        <div class="d-flex justify-content-start align-items-center pb-4 pl-3 border-bottom"> #}
        {#            <div class="text-muted"> #}
        {#                <button class="text-white btn">50% Discount</button> #}
        {#            </div> #}
        {#            <div class="ml-auto price"> #}
        {#                -$34.94 #}
        {#            </div> #}
        {#        </div> #}
        <div class="d-flex justify-content-start align-items-center pl-3 py-3 mb-4 border-bottom">
            <div class="text-muted">
                Today's Total&nbsp;
            </div>
            <div class="ml-auto h5">
                {{ order.getAmount(true)|format_currency("USD") }}
            </div>
        </div>
        <div class="row border rounded p-1 my-3">
            <div class="col-md-6 py-3">
                <div class="d-flex flex-column align-items start">
                    <b>Billing Address</b>
                    <p class="text-justify pt-2">{{ order.address.firstName }} {{ order.address.lastName }},
                        {{ order.address.addressLine1 }} {{ order.address.addressLine2 }}</p>
                    <p class="text-justify">{{ order.address.city }} {{ order.address.postalCode }} {{ order.address.state }}</p>
                </div>
            </div>
            <div class="col-md-6 py-3">
                <div class="d-flex flex-column align-items start">
                    <b>Shipping Address</b>
                    <p class="text-justify pt-2">{{ order.address.firstName }} {{ order.address.lastName }},
                        {{ order.address.addressLine1 }} {{ order.address.addressLine2 }}</p>
                    <p class="text-justify">{{ order.address.city }} {{ order.address.postalCode }} {{ order.address.state }}</p>
                </div>
            </div>
        </div>
        {# Invoices details get here #}
        {#        <div class="pl-3 font-weight-bold">Related Invoices (Implementation in progress)</div> #}
        {#        <div class="d-sm-flex justify-content-between rounded my-3 subscriptions"> #}
        {#            <div> #}
        {#                <b>#ID</b> #}
        {#            </div> #}
        {#            <div>createdAt</div> #}
        {#            <div>Status</div> #}
        {#            <div> #}
        {#                Total: <b> $USD for ? items</b> #}
        {#            </div> #}
        {#        </div> #}
    </div>
{% endblock %}

templates/order/index.html.twig
{% extends 'logged.html.twig' %}

{% block title %}Orders{% endblock %}

{% block body %}
    {% if app.debug %}
        <header class="py-5">
            <div class="container px-lg-3">
                <div class="p-2 p-lg-1 bg-light rounded-3 text-center">
                    <div class="m-4 m-lg-5">
                        <p class="fs-5">Subscriptions, like Products, are part of Doctrine Class Table Inheritance, Base
                            class for those
                            entities is App\Entity\CartItem. <br/> App\Entity\SubscriptionPlan Also implements two
                            interfaces: CartInsertableInterface, CartItemInterface
                        </p>
                    </div>
                </div>
            </div>
        </header>
    {% endif %}
    <section class="pt-4">
        <div class="container px-lg-3">
            <div class="row gx-lg-5">

                {% if paginator is not empty %}
                    <div class="list-group">
                        {% for order in paginator.results %}
                            {% include "order/partials/list_item.html.twig" with {'order': order} %}
                        {% endfor %}
                    </div>
                    {% include "pagination/paginator.html.twig" %}
                {% else %}
                    No orders placed yet
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}

templates/order/payment.html.twig
{% extends 'base.html.twig' %}
{% block title %}Payment{% endblock %}
{% block body %}
    <header>
        <div class="container px-lg-5">
            <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
                <div class="m-4 m-lg-5">
                    <p class="fs-5">We have accepted Your pending order request and simulated payment.<br/><br/>
                        For testing purposes and to not share any api keys for payment providers, app generated random
                        uuid for payment hash like value and store it in db<br/><br/>
                        For <strong>Yes</strong> option we will run OrderProcessing workflow and simulate
                        order and payment confirmation<br/>
                        For <strong>No</strong> option we will allow to revisit this page from orders page, or just
                        keep pending order for around 3 hours and then, delete order and restore stock.</p>
                </div>
            </div>
        </div>
    </header>
    <div class="container px-lg-5">
        {{ form(form) }}
    </div>
{% endblock %}

templates/order/pending.html.twig
{% extends 'base.html.twig' %}
{% block title %}Order{% endblock %}
{% block body %}
    <div class="row mt-5">
        <div class="col-md-9">
            {{ order.id }}
        </div>
        <div class="col-md-3">
        </div>
    </div>

{% endblock %}

templates/order/summary.html.twig
{% extends 'base.html.twig' %}
{% block title %}Order summary{% endblock %}
{% block body %}
    <div class="container mt-5 mb-5">
        <div class="row d-flex justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="text-left logo p-2 px-5">
                    </div>
                    <div class="invoice p-5">
                        <h5>Your order is Confirmed!</h5>
                        <span class="font-weight-bold d-block mt-4">Hello, {{ app.user.email }}</span>
                        <span>You order has been confirmed and will be shipped soon!</span>
                        <div class="payment border-top mt-3 mb-3 border-bottom table-responsive">
                            <table class="table table-borderless">
                                <tbody>
                                <tr>
                                    <td>
                                        <div class="py-2 text-nowrap">
                                            <span class="d-block text-muted pb-3">Order Date</span>
                                            <span>{{ order.createdAt|date("Y-m-d") }}</span>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="py-2 text-nowrap">
                                            <span class="d-block text-muted pb-3">Order No</span>
                                            <span>{{ order.id }}</span>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="py-2">
                                            <span class="d-block text-muted pb-3">Payment</span>
                                            <span>{{ order.lastPayment.operationType.value }}</span>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="py-2 text-right">
                                            <span class="d-block text-muted pb-3">Shipping Address</span>
                                            <span>{{ order.deliveryAddress.firstName }} {{ order.deliveryAddress.lastName }},<br/>
                        {{ order.deliveryAddress.addressLine1 }} {{ order.deliveryAddress.addressLine2 }}<br/>
                                            {{ order.deliveryAddress.city }} {{ order.deliveryAddress.postalCode }} {{ order.deliveryAddress.state }}
                                            </span>
                                        </div>
                                    </td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="product border-bottom table-responsive">
                            <table class="table table-borderless">
                                <tbody>
                                {% for item in order.items %}
                                    <tr>
                                        <td width="60%">
                                            <span class="font-weight-bold">{{ item.name }}</span>
                                            <div class="product-qty">
                                                <span class="d-block">Quantity: {{ item.quantity }}</span>
                                            </div>
                                        </td>
                                        <td width="20%">
                                            <div class="product-qty text-right">
                                                <span class="text-right">
                                                    {{ (item.price / 100)|format_currency("USD") }}
                                                </span>
                                                <span class="d-block font-weight-bold">
                                                    {{ ((item.quantity * item.price) / 100)|format_currency("USD") }}
                                                </span>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="row d-flex justify-content-end">
                            <div class="col-md-5">
                                <table class="table table-borderless">
                                    <tbody class="totals">
                                    <tr>
                                        <td>
                                            <div class="text-left">
                                                <span class="text-muted">Subtotal</span>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="text-right">
                                                <span>{{ (summary.subTotal / 100)|format_currency("USD") }}</span>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <div class="text-left">
                                                <span class="text-muted">Shipping Fee</span>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="text-right">
                                                <span>{{ (summary.shipping / 100)|format_currency("USD") }}</span>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr class="border-top border-bottom">
                                        <td>
                                            <div class="text-left">
                                                <span class="font-weight-bold">Total</span>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="text-right">
                                                <span
                                                    class="font-weight-bold">{{ (summary.total / 100)|format_currency("USD") }}</span>
                                            </div>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <p>We will be sending shipping confirmation email when the item shipped successfully!</p>
                        <span>Interview app team</span>
                    </div>
                    <div class="d-flex justify-content-between footer p-3">
                        <span>Need Help? you can submit  <a
                                href="https://github.com/RafalSalwa/interview-client-php/issues"> issue on github</a></span>
                        <span>{{ order.createdAt|date("Y-M-d") }}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}